plugins {
    id 'team.cagayakegirls.scripts'
    id 'dev.architectury.loom'
    id 'maven-publish'
}

group = "${project.maven_group}"
version = "${project.mod_version}+mc${project.minecraft_version}"
base.archivesName = "${project.archives_base_name}"

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings extraMappings.yarnWithPatch(project.yarn_mappings, "1.20.6+build.4")
    neoForge "net.neoforged:neoforge:${project.neoforge_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand "version": project.version
    }

    filteringCharset = 'UTF-8'
}

java {
    withSourcesJar()
    withJavadocJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = "org.thinkingstudio"
            artifactId = project.name.toLowerCase()
            version = "${project.mod_version}+mc${project.minecraft_version}"

            from components.java
        }
    }

    repositories {
        maven {
            name = "KTTMaven"
            url = "https://maven.kessokuteatime.work/releases"

            credentials {
                username = System.getenv("KTT_MAVEN_USERNAME")
                password = System.getenv("KTT_MAVEN_TOKEN")
            }
        }
    }
}
